### PR TITLE
CoinGecko

### PR DESCRIPTION
**Pull request by joaoescribano**
Added CoinGecko to the plugin (BTC, LTC, and ETN)
- [TODO] Need to add the provider getUrl method

I need help to understand how to get the CurrencyData into the provider getUrl so I can add the "coin name" variable to it and remove the "if statement" at the getUrl method.

### CODE REVIEW

**Comment by joaoescribano** [comment]
At the last commit i fixed the issue at the CurrencyData and the getUrl method.
Also added dogecoin support and BTC as currency pair.

image

**Comment by joaoescribano** [comment]
Added CoinGecko to the readme file

**Comment by OttoAllmendinger** [comment]
thanks for your work

I reworked the Provider interface and added CoinGecko here: https://github.com/OttoAllmendinger/gnome-shell-bitcoin-markets/commit/1726c7583ed42c39e51ba726bc3343f2539ca5c3

**Comment by tmlee** [comment]
Nice to see CoinGecko being implemented and added to this extension! Appreciate it!

**Pull request closed without merging**
